### PR TITLE
ZON-5728: Upgrade to selenium-3.x with geckodriver

### PR DESCRIPTION
**Pull request by wosc**
JENKINS_BATOU_BRANCH=selenium

Needs https://github.com/ZeitOnline/vivi-deployment/pull/93

### CODE REVIEW

**Comment by wosc** [comment]
run jenkins

**Comment by zon-hoppe** [comment]
run jenkins

**Comment by zon-hoppe** [comment]
run jenkins

**Comment by zon-hoppe** [comment]
run jenkins

**Comment by zon-hoppe** [comment]
run jenkins

**Comment by zon-hoppe** [comment]
run jenkins

**Pull request merged**
